###
POST http://localhost:8090/api/developers
Content-Type: application/json

{
  "name": "john",
  "category": "BACKEND",
  "experienceYear": 1

}



###
GET http://localhost:8090/api/developers




###
GET http://localhost:8090/api/developers/1

###
DELETE http://localhost:8090/api/developers/1


###
PATCH http://localhost:8090/api/developers/1
Content-Type: application/json

{
  "name": "tomSon",
  "category": "FRONTEND"
}

